# Generated by Django 4.2.7 on 2023-11-15 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quotes", "0003_alter_door_options_alter_window_options"),
        ("user", "0003_alter_customerprofile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_doorMaterial",
                    models.ManyToManyField(to="quotes.doormaterial"),
                ),
                ("selected_doorSize", models.ManyToManyField(to="quotes.doorsize")),
                ("selected_doors", models.ManyToManyField(to="quotes.door")),
                ("selected_windows", models.ManyToManyField(to="quotes.window")),
                (
                    "selected_wndwMaterial",
                    models.ManyToManyField(to="quotes.windowmaterial"),
                ),
                ("selected_wndwSize", models.ManyToManyField(to="quotes.windowsize")),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.customerprofile",
                    ),
                ),
            ],
        ),
    ]
