# Generated by Django 4.2.6 on 2023-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="company_address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="country_category",
            field=models.CharField(
                choices=[
                    ("afghanistan", "Afghanistan"),
                    ("albania", "Albania"),
                    ("algeria", "Algeria"),
                    ("south korea", "south korea"),
                    ("united states ", "United states"),
                    ("France", "France"),
                ],
                default="south korea",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="image",
            field=models.ImageField(null=True, upload_to="Profile_Images"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="region",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
