# Generated by Django 4.2.7 on 2023-11-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customerprofile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="image",
            field=models.ImageField(
                default="Profile_Images/1_0_0_20161219140623097.jpg",
                upload_to="Profile_Images",
            ),
        ),
    ]
