# Generated by Django 4.2.7 on 2023-11-06 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_windowmaterial_category_windowmaterial_quantity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="door",
            options={"verbose_name_plural": "문 "},
        ),
        migrations.AlterModelOptions(
            name="window",
            options={"verbose_name_plural": "창문들"},
        ),
    ]
