# Generated by Django 4.2.7 on 2023-11-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_alter_door_options_alter_window_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="door",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="window",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
